name: Build and deploy Github Pages
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Zola Build
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_ONLY: true
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
